import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { ok, err, ExitCode, type Result } from "@skillwiki/shared";
import { extractFrontmatter } from "../parsers/frontmatter.js";

export interface ProjectIndexInput {
  vault: string;
  slug: string;
  apply: boolean;
}

export interface IndexEntry {
  page: string;
  type: string;
  title: string;
}

export interface ProjectIndexOutput {
  slug: string;
  entries: IndexEntry[];
  existing: boolean;
  stale: boolean;
  index_path: string;
  humanHint: string;
}

const LAYER2_DIRS = ["entities", "concepts", "comparisons", "queries", "meta"];

export async function runProjectIndex(input: ProjectIndexInput): Promise<{ exitCode: number; result: Result<ProjectIndexOutput> }> {
  const slug = input.slug;
  const projectDir = join(input.vault, "projects", slug);

  // Check project exists
  try {
    await readdir(projectDir);
  } catch {
    return {
      exitCode: ExitCode.PROJECT_NOT_FOUND,
      result: err("PROJECT_NOT_FOUND", { slug, path: projectDir })
    };
  }

  const wikilinkPattern = `[[${slug}]]`;
  const entries: IndexEntry[] = [];

  // Scan Layer 2 pages for provenance_projects referencing this slug
  for (const dir of LAYER2_DIRS) {
    let files: Array<{ name: string; isFile: () => boolean }>;
    try {
      files = await readdir(join(input.vault, dir), { withFileTypes: true });
    } catch { continue; }

    for (const entry of files) {
      if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
      const filePath = join(input.vault, dir, entry.name);
      let text: string;
      try { text = await readFile(filePath, "utf8"); } catch { continue; }

      const fm = extractFrontmatter(text);
      if (!fm.ok) continue;

      // Check provenance_projects for [[slug]]
      const pp = fm.data.provenance_projects;
      if (!Array.isArray(pp) || !pp.some((p: unknown) => String(p) === wikilinkPattern)) continue;

      entries.push({
        page: `${dir}/${entry.name}`,
        type: fm.data.type ?? dir.slice(0, -1), // singularize dir name
        title: fm.data.title ?? entry.name.replace(/\.md$/, "")
      });
    }
  }

  // Sort: entities first, then concepts, then rest; within group by title
  const typeOrder: Record<string, number> = { entity: 0, concept: 1, comparison: 2, query: 3, summary: 4, meta: 5 };
  entries.sort((a, b) => {
    const ta = typeOrder[a.type] ?? 99;
    const tb = typeOrder[b.type] ?? 99;
    return ta !== tb ? ta - tb : a.title.localeCompare(b.title);
  });

  const indexPath = join(projectDir, "knowledge.md");

  // Check if existing index is stale
  let existing = false;
  let stale = false;
  try {
    const existingText = await readFile(indexPath, "utf8");
    existing = true;
    // Compare entry count and page list
    const existingEntries = existingText.split("\n").filter(l => l.startsWith("- [["));
    const existingPages = new Set(existingEntries.map(l => {
      const m = l.match(/\[\[([^\]]+)\]\]/);
      return m ? m[1] : "";
    }));
    const currentPages = new Set(entries.map(e => e.page.replace(/\.md$/, "")));
    stale = existingPages.size !== currentPages.size || [...currentPages].some(p => !existingPages.has(p));
  } catch { /* no existing index */ }

  // Generate index content
  const today = new Date().toISOString().slice(0, 10);
  const grouped = new Map<string, IndexEntry[]>();
  for (const e of entries) {
    const group = e.type;
    if (!grouped.has(group)) grouped.set(group, []);
    grouped.get(group)!.push(e);
  }

  let body = `# Knowledge Index: ${slug}\n\nAutogenerated by \`skillwiki project-index\` on ${today}.\n\n`;
  for (const [type, items] of grouped) {
    body += `## ${type}\n\n`;
    for (const item of items) {
      const pageRef = item.page.replace(/\.md$/, "");
      body += `- [[${pageRef}]] — ${item.title}\n`;
    }
    body += "\n";
  }

  if (entries.length === 0) {
    body += `No Layer 2 pages reference \`[[${slug}]]\` in provenance_projects.\n`;
  }

  if (input.apply) {
    try {
      await mkdir(dirname(indexPath), { recursive: true });
      await writeFile(indexPath, body, "utf8");
    } catch (e) {
      return {
        exitCode: ExitCode.WRITE_FAILED,
        result: err("WRITE_FAILED", { file: indexPath, message: String(e) })
      };
    }
  }

  const action = input.apply
    ? `written ${entries.length} entries to ${indexPath}`
    : `${entries.length} entries found (use --apply to write)`;
  const staleHint = stale ? " (STALE — existing index outdated)" : existing ? " (up to date)" : "";

  return {
    exitCode: ExitCode.OK,
    result: ok({
      slug,
      entries,
      existing,
      stale,
      index_path: `projects/${slug}/knowledge.md`,
      humanHint: `project: ${slug}\nentries: ${entries.length}${staleHint}\n${action}\n\n${entries.map(e => `  ${e.type}: [[${e.page.replace(/\.md$/, "")}]] — ${e.title}`).join("\n")}`
    })
  };
}
