import { describe, expect, it } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { renderRootIndex } from "../../src/utils/index-projection.js";

const FM = (title: string, type: string) => `---
title: ${title}
type: ${type}
tags: []
sources: [raw/articles/seed.md]
provenance: research
created: 2026-07-15
updated: 2026-07-15
---

# ${title}
`;

describe("renderRootIndex", () => {
  it("renders deterministic sections, drops ghosts/duplicates, preserves unmanaged block", async () => {
    const vault = mkdtempSync(join(tmpdir(), "index-projection-"));
    writeFileSync(join(vault, "SCHEMA.md"), "# Schema\n");
    for (const d of ["entities", "concepts", "comparisons", "queries", "meta"]) {
      mkdirSync(join(vault, d), { recursive: true });
    }
    mkdirSync(join(vault, "projects", "demo"), { recursive: true });
    writeFileSync(join(vault, "entities", "acme.md"), FM("ACME Corporation", "entity"));
    writeFileSync(join(vault, "concepts", "alpha.md"), FM("Alpha Concept", "concept"));
    writeFileSync(join(vault, "projects", "demo", "README.md"), "# Project: Demo Project\n\nDesc.\n");
    writeFileSync(
      join(vault, "index.md"),
      `# Vault Index

## entities
- [[concepts/missing]] — ghost
- [[entities/acme]] — ACME Corporation
- [[entities/acme]] — ACME Corporation

## Entities
- [[concepts/alpha]] — Alpha Concept

<!-- skillwiki:index-unmanaged:start -->
Operator-maintained navigation note.
<!-- skillwiki:index-unmanaged:end -->
`,
    );

    const projection = await renderRootIndex({ vault });
    expect(projection.ok).toBe(true);
    if (!projection.ok) return;

    expect(projection.data.text).toBe(`# Vault Index

Generated by \`skillwiki index rebuild\`. Generated sections are derived from typed-page frontmatter and project manifests.

## Entities

- [[entities/acme]] — ACME Corporation

## Concepts

- [[concepts/alpha]] — Alpha Concept

## Comparisons

## Queries

## Meta

## Projects

- [[projects/demo/README]] — Demo Project

<!-- skillwiki:index-unmanaged:start -->
Operator-maintained navigation note.
<!-- skillwiki:index-unmanaged:end -->
`);

    expect(projection.data.entries.map((entry) => entry.target)).toEqual([
      "entities/acme",
      "concepts/alpha",
      "projects/demo/README",
    ]);
    expect(projection.data.duplicates_removed).toBeGreaterThan(0);
    expect(projection.data.ghosts_removed).toContain("concepts/missing");
  });
});
