import { describe, it, expect } from "vitest";
import { ExitCode, exitCodeName } from "./exit-codes.js";

describe("exit-codes", () => {
  it("declares every code from the spec Command Contracts table", () => {
    expect(ExitCode.OK).toBe(0);
    expect(ExitCode.INTERNAL_ERROR).toBe(1);
    expect(ExitCode.FILE_NOT_FOUND).toBe(2);
    expect(ExitCode.MISSING_CLOSING_DELIMITER).toBe(3);
    expect(ExitCode.SCHEME_REJECTED).toBe(4);
    expect(ExitCode.HOST_BLOCKED).toBe(5);
    expect(ExitCode.MALFORMED_URL).toBe(6);
    expect(ExitCode.INVALID_FRONTMATTER).toBe(7);
    expect(ExitCode.SCHEMA_NOT_DETECTED).toBe(8);
    expect(ExitCode.VAULT_PATH_INVALID).toBe(9);
    expect(ExitCode.WRITE_FAILED).toBe(10);
    expect(ExitCode.UNRESOLVED_MARKERS).toBe(11);
    expect(ExitCode.SOURCES_INCONSISTENT).toBe(12);
    expect(ExitCode.PREFLIGHT_FAILED).toBe(13);
    expect(ExitCode.ATOMIC_COPY_FAILED).toBe(14);
    expect(ExitCode.INIT_TARGET_NOT_EMPTY).toBe(15);
    expect(ExitCode.BROKEN_WIKILINKS).toBe(16);
    expect(ExitCode.TAG_NOT_IN_TAXONOMY).toBe(17);
    expect(ExitCode.INDEX_INCOMPLETE).toBe(18);
    expect(ExitCode.STALE_PAGE).toBe(19);
    expect(ExitCode.PAGE_TOO_LARGE).toBe(20);
    expect(ExitCode.LOG_ROTATE_NEEDED).toBe(21);
    expect(ExitCode.LINT_HAS_WARNINGS).toBe(22);
    expect(ExitCode.LINT_HAS_ERRORS).toBe(23);
    expect(ExitCode.ENV_WRITE_CONFLICT).toBe(24);
    expect(ExitCode.NO_VAULT_CONFIGURED).toBe(25);
    expect(ExitCode.INVALID_CONFIG_KEY).toBe(26);
    expect(ExitCode.CONFIG_WRITE_FAILED).toBe(27);
    expect(ExitCode.DOCTOR_HAS_WARNINGS).toBe(28);
    expect(ExitCode.DOCTOR_HAS_ERRORS).toBe(29);
    expect(ExitCode.ARCHIVE_TARGET_NOT_FOUND).toBe(30);
    expect(ExitCode.ARCHIVE_ALREADY_ARCHIVED).toBe(31);
    expect(ExitCode.DRIFT_DETECTED).toBe(32);
    expect(ExitCode.RAW_DEDUP_DETECTED).toBe(33);
    expect(ExitCode.MIGRATION_APPLIED).toBe(34);
    expect(ExitCode.UNKNOWN_WIKI_PROFILE).toBe(35);
    expect(ExitCode.DEDUP_APPLIED).toBe(36);
    expect(ExitCode.PROJECT_NOT_FOUND).toBe(37);
    expect(ExitCode.SYMLINK_FAILED).toBe(38);
    expect(ExitCode.COMPOUND_PROMOTED).toBe(39);
    expect(ExitCode.SKILL_VERSION_MISMATCH).toBe(40);
    expect(ExitCode.INGEST_VALIDATION_FAILED).toBe(41);
    expect(ExitCode.FLEET_MANIFEST_INVALID).toBe(50);
    expect(ExitCode.SENSITIVE_CONTENT_DETECTED).toBe(51);
    expect(ExitCode.FLEET_SATELLITE_HEALTH_FAILED).toBe(52);
    expect(ExitCode.PROTECTED_SNAPSHOTTER_WRITE_BLOCKED).toBe(53);
    expect(ExitCode.SYNC_LOCK_HELD).toBe(48);
    expect(ExitCode.LOG_APPEND_LOCK_HELD).toBe(49);
  });

  it("exposes a stable name for every code (non-empty, unique)", () => {
    const codes = Object.values(ExitCode).filter(v => typeof v === "number") as number[];
    const names = codes.map(c => exitCodeName(c));
    expect(new Set(names).size).toBe(names.length);
    for (const n of names) expect(n.length).toBeGreaterThan(0);
    expect(exitCodeName(51)).toBe("SENSITIVE_CONTENT_DETECTED");
    expect(exitCodeName(53)).toBe("PROTECTED_SNAPSHOTTER_WRITE_BLOCKED");
  });
});
