import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { err, ok, type Result } from "@skillwiki/shared";
import { atomicWriteText } from "./atomic-write.js";
import {
  buildRootIndexUniverse,
  ROOT_INDEX_SECTION_ORDER,
  type RootIndexEntry,
} from "./index-universe.js";

export type { RootIndexEntry } from "./index-universe.js";

export const UNMANAGED_START = "<!-- skillwiki:index-unmanaged:start -->";
export const UNMANAGED_END = "<!-- skillwiki:index-unmanaged:end -->";

export interface RootIndexProjection {
  text: string;
  entries: RootIndexEntry[];
  duplicates_removed: number;
  ghosts_removed: string[];
}

export interface RenderRootIndexInput {
  vault: string;
  currentText?: string;
}

function extractUnmanaged(currentText: string): Result<string> {
  const startCount = currentText.split(UNMANAGED_START).length - 1;
  const endCount = currentText.split(UNMANAGED_END).length - 1;
  if (startCount === 0 && endCount === 0) return ok("");
  if (startCount !== 1 || endCount !== 1) {
    return err("SCHEME_REJECTED", {
      message: "index.md must contain exactly one complete unmanaged marker pair",
    });
  }
  const start = currentText.indexOf(UNMANAGED_START);
  const end = currentText.indexOf(UNMANAGED_END);
  if (start < 0 || end < 0 || end < start) {
    return err("SCHEME_REJECTED", {
      message: "unmanaged marker pair is reversed or incomplete",
    });
  }
  const body = currentText.slice(start + UNMANAGED_START.length, end).replace(/^\n/, "").replace(/\n$/, "");
  return ok(body);
}

function priorWikilinkTargets(text: string): string[] {
  const out: string[] = [];
  const re = /\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    out.push(m[1]!.trim().replace(/\.md$/, ""));
  }
  return out;
}

export async function renderRootIndex(
  input: RenderRootIndexInput,
): Promise<Result<RootIndexProjection>> {
  const vault = input.vault;
  let currentText = input.currentText;
  if (currentText === undefined) {
    try {
      currentText = await readFile(join(vault, "index.md"), "utf8");
    } catch {
      currentText = "";
    }
  }

  const unmanaged = extractUnmanaged(currentText);
  if (!unmanaged.ok) return unmanaged;

  const universe = await buildRootIndexUniverse({ vault });
  if (!universe.ok) return universe;
  const entries: RootIndexEntry[] = universe.data.required;
  let duplicatesRemoved = universe.data.duplicatesRemoved;

  const prior = priorWikilinkTargets(currentText);
  const knownTargets = universe.data.knownTargets;
  const knownBasenames = new Set(
    [...knownTargets].map((target) => target.split("/").pop()!.toLowerCase()),
  );
  // Count prior generated-section duplicates (case-folded target collisions in prior index)
  const priorLower = new Map<string, number>();
  for (const t of prior) {
    const k = t.toLowerCase();
    priorLower.set(k, (priorLower.get(k) ?? 0) + 1);
  }
  for (const count of priorLower.values()) {
    if (count > 1) duplicatesRemoved += count - 1;
  }
  // Also count prior section heading case-duplicates as diagnostic when both
  // "entities" and "Entities" style appear as separate ## headings for same type.
  const headingDupes = (currentText.match(/^##\s+(entities|concepts|comparisons|queries|meta|projects)\s*$/gim) ?? [])
    .map((h) => h.replace(/^##\s+/i, "").trim().toLowerCase());
  const headingCounts = new Map<string, number>();
  for (const h of headingDupes) headingCounts.set(h, (headingCounts.get(h) ?? 0) + 1);
  for (const c of headingCounts.values()) {
    if (c > 1) duplicatesRemoved += c - 1;
  }

  const ghostsRemoved = [
    ...new Set(
      prior.filter((t) => {
        if (!t.includes("/")) {
          return !knownBasenames.has(t.toLowerCase());
        }
        return !knownTargets.has(t);
      }),
    ),
  ];

  const lines: string[] = [
    "# Vault Index",
    "",
    "Generated by `skillwiki index rebuild`. Generated sections are derived from typed-page frontmatter and project manifests.",
    "",
  ];

  for (const section of ROOT_INDEX_SECTION_ORDER) {
    lines.push(`## ${section}`, "");
    const sectionEntries = entries.filter((e) => e.section === section);
    for (const e of sectionEntries) {
      lines.push(`- [[${e.target}]] — ${e.title}`);
    }
    if (sectionEntries.length > 0) lines.push("");
  }

  lines.push(UNMANAGED_START);
  if (unmanaged.data) {
    lines.push(unmanaged.data);
  }
  lines.push(UNMANAGED_END);
  lines.push("");

  return ok({
    text: lines.join("\n"),
    entries,
    duplicates_removed: duplicatesRemoved,
    ghosts_removed: ghostsRemoved,
  });
}

export async function writeRootIndexProjection(
  vault: string,
  projection: RootIndexProjection,
): Promise<Result<{ changed: boolean }>> {
  return atomicWriteText(join(vault, "index.md"), projection.text);
}
