import type { SkillwikiLogEventV1 } from "./log-events.js";

function day(event: SkillwikiLogEventV1): string {
  return event.occurred_at.slice(0, 10);
}

function marker(event: SkillwikiLogEventV1): string {
  return `<!-- skillwiki-log-event:${event.operation_id} -->`;
}

function bodyFor(event: SkillwikiLogEventV1): string {
  if (event.kind === "page-publish") {
    const tax = Array.isArray(event.metadata.taxonomy_added)
      ? (event.metadata.taxonomy_added as string[])
      : [];
    return [
      `- Published: [[${event.target.replace(/\.md$/, "")}]]`,
      `- Taxonomy: ${tax.length > 0 ? `added ${tax.join(", ")}` : "no additions"}`,
      event.note ? `- Note: ${event.note}` : "",
    ].filter(Boolean).join("\n");
  }
  if (event.kind === "legacy-log-entry" && typeof event.metadata.legacy_markdown === "string") {
    const legacy = event.metadata.legacy_markdown.trimEnd();
    if (legacy.includes(marker(event))) return legacy;
    return `${legacy}\n${marker(event)}`;
  }
  if (event.kind === "session-brief" || event.kind === "archive" || event.kind === "remove" || event.kind === "log-entry") {
    return [
      `- Target: ${event.target}`,
      `- Note: ${event.note}`,
      `- Actor: ${event.actor}`,
      `- Host: ${event.host_id}`,
    ].join("\n");
  }
  return [
    `- Event kind: ${event.kind}`,
    `- Actor: ${event.actor}`,
    `- Host: ${event.host_id}`,
    `- Target: ${event.target}`,
    `- Note: ${event.note}`,
    `- Metadata: ${JSON.stringify(event.metadata)}`,
  ].join("\n");
}

/** Deterministic root-log Markdown from ordered immutable events. */
export function renderLogProjection(events: readonly SkillwikiLogEventV1[]): string {
  const ordered = [...events].sort((a, b) => {
    if (a.occurred_at !== b.occurred_at) return a.occurred_at < b.occurred_at ? -1 : 1;
    return a.operation_id < b.operation_id ? -1 : a.operation_id > b.operation_id ? 1 : 0;
  });
  const lines = [
    "# Vault Log",
    "",
    "Generated by `skillwiki log materialize` from immutable events.",
    "",
  ];
  for (const event of ordered) {
    if (event.kind === "legacy-log-entry" && typeof event.metadata.legacy_markdown === "string") {
      const block = bodyFor(event);
      lines.push(block.endsWith("\n") ? block.trimEnd() : block, "");
      continue;
    }
    lines.push(`## [${day(event)}] ${event.kind} | ${event.target}`, "", bodyFor(event), marker(event), "");
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}
