#!/usr/bin/env bash
# AUTO-GENERATED by packages/vault-sync/scripts/generate-systemd-property-catalog.mjs.
# Source: packages/shared/src/systemd-property-catalog.json
# Do not edit this file directly.

snapshot_semantic_to_systemd_prop() {
  case "$1" in
    load_state) printf 'LoadState\n' ;;
    unit_file_state) printf 'UnitFileState\n' ;;
    active_state) printf 'ActiveState\n' ;;
    sub_state) printf 'SubState\n' ;;
    next_elapse) printf 'NextElapseUSecRealtime\n' ;;
    result) printf 'Result\n' ;;
    exec_main_status) printf 'ExecMainStatus\n' ;;
    exec_main_code) printf 'ExecMainCode\n' ;;
    active_enter_timestamp) printf 'ActiveEnterTimestamp\n' ;;
    inactive_enter_timestamp) printf 'InactiveEnterTimestamp\n' ;;
    exec_main_start_timestamp) printf 'ExecMainStartTimestamp\n' ;;
    exec_main_exit_timestamp) printf 'ExecMainExitTimestamp\n' ;;
    invocation_id) printf 'InvocationID\n' ;;
    # Closed map: never pass unknown/snake_case keys through to systemctl.
    *) return 1 ;;
  esac
}
